# You'd better do not touch this.
do-not-touch-me-please: 11451419
# The name of configuration section is really easy to understand.
# See Wiki for details.
#
# More info:
# Supported Economy Types:
#   - PLUGIN_VAULT
#   - PLUGIN_PLAYERPOINTS
#   - PLUGIN_XCONOMY
#   - MINECRAFT_EXP_LEVEL
#Supported language:
#   - en
#   - zh_CN