name: ValuableForceload
version: '1.0.4f3'
main: me.eventually.valuableforceload.ValuableForceload
api-version: '1.13'
load: POSTWORLD
authors: [ Eventually ]
folia-supported: true
description: A plugin that allows players to buy force-load chunks for certain times.
softdepend:
  - Vault
  - PlayerPoints
  - XConomy
commands:
  valuableforceload:
    description: "ValuableForceload main command"
    aliases:
      - fl
      - vfl
      - vforceload
    permission-message: "You do not have permission to use this command."
    usage: "/valuableforceload <open|version|admin|reload>"